[Evo] PWA - Show DM/room's last message on home screen
WideChat/Rocket.Chat pull request #90
Opened 2019-11-09 19:43 UTC by Kailash0311

- Fixes [Issue](https://github.com/WideChat/pwa/issues/21)

- Make extended-sidebar _default_ and _unchangeable_ in mobile.
- The desktop version remains the same.

This is developed on this [PR](https://github.com/WideChat/Rocket.Chat/pull/83).

2019-11-09 20:56 UTC, kb0304 commented
@Kailash0311 Can you please create a PR to branch `karan_pwa_3`. Thanks.

2019-11-12 16:26 UTC, kb0304 requested changes

2019-11-12 16:26 UTC, kb0304 commented on app/ui-sidenav/client/sideNav.js
> +		if (/Mobi/.test(navigator.userAgent)) {
Can we create a helper method to determine if the client is a mobile client and use that helper function everywhere?

2019-11-12 18:46 UTC, Kailash0311 commented
Added a `isMobile` function in `app/utils/client/lib`

2019-11-14 16:09 UTC, kb0304 approved these changes

2019-11-14 16:10 UTC, merged